module.exports = async function handler(req, res) {
  res.setHeader('Content-Type', 'application/json');

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    let body = req.body;
    if (typeof body === 'string') {
      try {
        body = JSON.parse(body);
      } catch (e) {
        return res.status(400).json({ error: 'Invalid JSON payload sent to server.' });
      }
    }

    const imageBase64 = body ? body.imageBase64 : null;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ 
        error: "GEMINI_API_KEY is missing in Vercel Environment Variables!" 
      });
    }

    if (!imageBase64 || typeof imageBase64 !== 'string') {
      return res.status(400).json({ error: "No valid image data payload received." });
    }

    // STEP 1: Ask Gemini which models are active for this API key
    const listModelsRes = await fetch(`https://generativelanguage.googleapis.com/v1beta/models?key=${apiKey}`);
    const listModelsData = await listModelsRes.json();

    if (!listModelsRes.ok || !listModelsData.models) {
      return res.status(listModelsRes.status || 500).json({
        error: `API Key error: ${listModelsData.error?.message || 'Failed to list models.'}`
      });
    }

    // Filter models that support content generation
    const availableModels = listModelsData.models
      .filter(m => m.supportedGenerationMethods && m.supportedGenerationMethods.includes('generateContent'))
      .map(m => m.name); // Returns format like "models/gemini-..."

    if (availableModels.length === 0) {
      return res.status(500).json({ error: "No available models found for this API key." });
    }

    // Prefer flash models, otherwise take the first active model returned
    const selectedModel = availableModels.find(m => m.includes('flash')) || availableModels[0];

    // STEP 2: Process image data
    const parts = imageBase64.split(',');
    if (parts.length < 2) {
      return res.status(400).json({ error: "Malformed image base64 data." });
    }

    const mimeMatch = parts[0].match(/:(.*?);/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/jpeg';
    const base64Data = parts[1];

    const promptText = 'Analyze this image carefully. Does this image contain a real or clearly visible flying bird? Respond strictly with a JSON object in this exact format: {"correct": true} or {"correct": false}.';

    // STEP 3: Send request to the active model endpoint
    const apiResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/${selectedModel}:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: promptText },
              { inlineData: { mimeType: mimeType, data: base64Data } }
            ]
          }
        ],
        generationConfig: {
          responseMimeType: "application/json"
        }
      })
    });

    const data = await apiResponse.json();

    if (!apiResponse.ok) {
      return res.status(apiResponse.status || 500).json({ 
        error: data.error?.message || `Model ${selectedModel} returned an error.` 
      });
    }

    const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!textResult) {
      return res.status(500).json({ error: "No response generated by AI." });
    }

    const cleanedText = textResult.replace(/```json|```/g, '').trim();
    const cleanJson = JSON.parse(cleanedText);

    return res.status(200).json(cleanJson);

  } catch (error) {
    return res.status(500).json({ 
      error: error.message || "Internal server error occurred." 
    });
  }
};
