module.exports = async function handler(req, res) {
  // Always set JSON header
  res.setHeader('Content-Type', 'application/json');

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method Not Allowed' });
  }

  try {
    // 1. Safe Body Parsing (handles string or object)
    let body = req.body;
    if (typeof body === 'string') {
      try {
        body = JSON.parse(body);
      } catch (e) {
        return res.status(400).json({ error: 'Invalid JSON payload sent to server.' });
      }
    }

    const imageBase64 = body ? body.imageBase64 : null;
    const apiKey = process.env.GEMINI_API_KEY;

    // 2. Check for API Key
    if (!apiKey) {
      return res.status(500).json({ 
        error: "GEMINI_API_KEY is missing in Vercel Environment Variables!" 
      });
    }

    // 3. Check for Image Data
    if (!imageBase64 || typeof imageBase64 !== 'string') {
      return res.status(400).json({ error: "No valid image data payload received." });
    }

    // Extract mime type and base64 string
    const parts = imageBase64.split(',');
    if (parts.length < 2) {
      return res.status(400).json({ error: "Malformed image base64 data." });
    }

    const mimeMatch = parts[0].match(/:(.*?);/);
    const mimeType = mimeMatch ? mimeMatch[1] : 'image/jpeg';
    const base64Data = parts[1];

    const promptText = 'Analyze this image. Does this image contain a real or clearly visible flying bird? Respond strictly with a JSON object in this exact format: {"correct": true} or {"correct": false}.';

    // 4. Call Gemini API
    const apiResponse = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          {
            parts: [
              { text: promptText },
              { inlineData: { mimeType: mimeType, data: base64Data } }
            ]
          }
        ],
        generationConfig: {
          responseMimeType: "application/json"
        }
      })
    });

    const data = await apiResponse.json();

    if (!apiResponse.ok) {
      return res.status(apiResponse.status || 500).json({ 
        error: data.error?.message || "Gemini API rejected request." 
      });
    }

    const textResult = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!textResult) {
      return res.status(500).json({ error: "No response text generated by AI." });
    }

    const cleanedText = textResult.replace(/```json|```/g, '').trim();
    const cleanJson = JSON.parse(cleanedText);

    return res.status(200).json(cleanJson);

  } catch (error) {
    return res.status(500).json({ 
      error: error.message || "Internal server error occurred." 
    });
  }
};
